import { useEffect, useState } from 'react';

type Category = 'drawing' | 'sketches' | 'illustrations' | 'photography' | 'school-projects' | 'graphic-design' | 'traditional-sketches';
type Artwork = { id:string; title:string; note:string; originalFilename:string; category:Category; image:string; featured?:boolean; order:number };

const collections: Record<Category, {number:string; name:string; verb:string; introduction:string; accent:string}> = {
  drawing: {number:'01', name:'Dessins', verb:'Observer', accent:'graphite', introduction:'Études de visage, de main, d’anatomie et de présence. Le regard commence ici, par ce qui est vu.'},
  sketches: {number:'02', name:'Croquis', verb:'Chercher', accent:'paper', introduction:'Un laboratoire de lignes rapides, de postures et de recherches laissées volontairement ouvertes.'},
  illustrations: {number:'03', name:'Illustrations', verb:'Imaginer', accent:'vermilion', introduction:'Des images plus affirmées, où la couleur et la composition prolongent le geste du dessin.'},
  photography: {number:'04', name:'Photographie', verb:'Cadrer', accent:'night', introduction:'Des fragments retenus par le cadre : lumière, distance, rythme et détail.'},
  'school-projects': {number:'05', name:'Projets scolaires', verb:'Construire', accent:'ochre', introduction:'Affiches, systèmes et supports conçus dans le cadre de recherches appliquées.'},
  'graphic-design': {number:'06', name:'Design graphique', verb:'Communiquer', accent:'ink', introduction:'Une image pensée pour être lue, reconnue et faire circuler une idée.'},
  'traditional-sketches': {number:'07', name:'Croquis traditionnels', verb:'Tracer', accent:'earth', introduction:'La feuille, le bureau, le stylo : le temps du geste et la matière réelle.'}
};

const files: Record<Category, string[]> = {
  drawing:['1782435152728','observation','img-20260626-004004-104','anatomie','mains','1782414372620','portrait'],
  sketches:['1784077176551','1784077179368','1784077183491','1784077192873','1784077196263','1784077199192','1784077203887','1784077207687','1784077227077','1784077229966','1784077236145','1784077238456','1784077241017','1784077244198'],
  illustrations:['rahhhhh-ttt','jesus22','collabbbbbrr','mtl','hn','com-2025','number-1'],
  photography:['img-20260102-005847-245-70101640','img-20251231-113900-580-1944823730','img-20251230-164810-896-1119577469','img-20251230-164602-592-1371120361','img-20251230-162756-988-478238756','img-20251230-161949-969-63003246','img-20251230-161710-439-1189738396','img-20260330-152014-917','img-20260128-024752-107','img-20260128-024400-270','img-20260128-023245-329','img-20260128-011915-433','img-20260116-173108-986'],
  'school-projects':['1784541226481','affiche','affiche-femme-glissante','affiche-femme','affiche-lebron','affiche-mascotte','emballage-du-produit-cofi'],
  'graphic-design':['hn1','roua-copie','after-work-revisiter-orig','maquette-originel-de-dos','maquette-originel-h24','panini-etiquette-copie'],
  'traditional-sketches':['bic','img-20260320-220227-940','img-20260320-215246-220','img-20260320-215209-755','img-20241219-072301-22','img-20241219-133055-658','img-20250815-175339-354','img-20250815-174416-209','img-20250815-175842-361','img-20250815-180051-141']
};
const artworkCopy: Record<Category, Array<[string,string]>> = {
  drawing:[['Étude de visage','Un travail d’observation où le trait cherche avant tout la présence.'],['Observation','Une étude attentive du modèle, construite par les valeurs et les contours.'],['Figure en mouvement','Une silhouette saisie dans un moment de tension et d’équilibre.'],['Anatomie','Recherche autour de la structure du corps et de ses volumes.'],['Étude de mains','Une série consacrée aux gestes, aux articulations et à l’expression des mains.'],['Étude de figure','Une recherche de proportions, de rythme et de placement dans la page.'],['Portrait','Un visage traité comme une rencontre entre caractère et lumière.']],
  sketches:[['Recherche 01','Croquis de posture, direct et sans correction superflue.'],['Recherche 02','Étude de mouvement à partir d’une ligne continue.'],['Recherche 03','Une silhouette construite par masses et contrepoids.'],['Recherche 04','Variation autour de la pose et de l’espace négatif.'],['Recherche 05','Recherche rapide, pensée comme une note de carnet.'],['Recherche 06','Le trait s’attarde sur la torsion du corps et les plis.'],['Recherche 07','Une scène de figure, retenue dans l’énergie du croquis.'],['Recherche 08','Dessin d’observation où la ligne devient volume.'],['Recherche 09','Étude de présence et de posture.'],['Recherche 10','Une recherche de structure, de texture et de rythme.'],['Recherche 11','Croquis à l’encre bleue, entre étude anatomique et mouvement.'],['Recherche 12','Une figure esquissée avec économie de moyens.'],['Recherche 13','Recherche de composition autour du corps dans l’espace.'],['Recherche 14','Un instant de dessin, gardé vivant par les traits de construction.']],
  illustrations:[['Rupture','Une illustration sombre où le personnage devient le point de friction de l’image.'],['Figure sacrée','Une composition centrée sur le regard, la matière et le contraste.'],['Collaboration','Une image conçue comme un échange de styles et de sensibilités.'],['MTL','Illustration numérique à la palette dense et aux formes affirmées.'],['HN','Une figure stylisée, travaillée comme une présence graphique.'],['COM 2025','Une composition pensée pour l’impact, l’affiche et la lecture immédiate.'],['Number One','Une image typographique où le personnage et le signe se répondent.']],
  photography:[['Lumière basse','Un cadrage où la lumière pose le premier plan et le silence.'],['Matière','Roches, mousses et reliefs : une étude de texture naturelle.'],['Reflet','Une image tenue par les surfaces, la couleur et la profondeur.'],['En suspension','La lumière isole un détail et change l’échelle du regard.'],['Passage','Une photographie de rythme, entre espace construit et instant saisi.'],['Contour','Un fragment observé pour ses lignes, ses ombres et sa densité.'],['Éclat','Une composition attentive aux contrastes et à la vibration de la couleur.'],['Hors saison','Un paysage ou un détail traité comme une image autonome.'],['Bleu profond','Une recherche photographique autour d’une tonalité et de ses nuances.'],['Rythme urbain','L’architecture et la lumière organisent le cadre.'],['Après l’averse','Une image de détails, de reflets et de matière.'],['Veille','Un moment calme, construit par la lumière disponible.'],['Dernière lumière','Une photographie qui privilégie l’atmosphère à l’anecdote.']],
  'school-projects':[['Projet éditorial','Recherche d’image et de hiérarchie pour un support de communication.'],['Affiche','Une proposition typographique conçue pour être vue à distance.'],['Femme glissante','Affiche de mouvement, entre narration visuelle et composition.'],['Figure','Une image qui met le personnage au centre de la lecture.'],['LeBron','Une affiche sportive pensée autour de la présence et de l’impact.'],['Mascotte','Travail d’identité et de caractère pour une figure illustrée.'],['Cofi — emballage','Recherche de packaging : forme, couleur et reconnaissance du produit.']],
  'graphic-design':[['HN1','Affiche illustrée : un univers narratif, dense et frontal.'],['ROUA','Une composition graphique où l’image et le signe partagent l’espace.'],['After Work','Visuel d’événement pensé pour l’énergie, le contraste et la nuit.'],['Maquette — dos','Étude de placement graphique sur vêtement.'],['Maquette H24','Proposition textile construite autour d’un emblème central.'],['Étiquette Panini','Une étiquette qui joue avec le format, la couleur et l’objet.']],
  'traditional-sketches':[['BIC','Un dessin au stylo où l’accident du trait fait partie de l’image.'],['Étude au stylo 01','Recherche de matière et de densité par la répétition du trait.'],['Étude au stylo 02','Une figure construite lentement, entre hachures et contours.'],['Étude au stylo 03','Le stylo comme outil de précision et de mouvement.'],['Carnet — matin','Une étude de carnet, gardée dans sa spontanéité.'],['Carnet — figure','Une recherche au stylo autour d’une silhouette et de ses volumes.'],['Carnet — détail','Une image de proximité, attentive aux textures.'],['Carnet — pause','Une étude brève où le trait capture une posture.'],['Carnet — construction','Les lignes de recherche restent visibles et font partie de la composition.'],['Carnet — dernière page','Une étude finale, plus libre, entre observation et interprétation.']]
};
const originalExtensions:Record<Category,string> = {drawing:'png',sketches:'png',illustrations:'jpg',photography:'jpg','school-projects':'jpg','graphic-design':'jpg','traditional-sketches':'jpg'};
const artworks:Artwork[] = (Object.keys(files) as Category[]).flatMap(category => files[category].map((file,index) => {
  const [title,note] = artworkCopy[category][index] ?? [`Recherche ${index+1}`,'Une pièce issue du portfolio d’Emmanuel.'];
  return { id:`${category}-${index+1}`, title, note, originalFilename:`${String(index+1).padStart(2,'0')}-${file}.${originalExtensions[category]}`, category, image:`/artworks/${category}/${String(index+1).padStart(2,'0')}-${file}.webp`, featured:index===0, order:index+1 };
}));

function useLocation(){ const [hash,setHash]=useState(location.hash || '#/'); useEffect(()=>{const fn=()=>setHash(location.hash||'#/'); addEventListener('hashchange',fn); return()=>removeEventListener('hashchange',fn)},[]); return hash; }
const go=(path:string)=>{location.hash=path; window.scrollTo({top:0,behavior:'instant' as ScrollBehavior})};
function ArtworkCard({artwork, open}:{artwork:Artwork;open:()=>void}){ const c=collections[artwork.category]; return <button className={`art-card ${c.accent}`} onClick={open} aria-label={`Ouvrir ${artwork.title}`}><img loading="lazy" src={artwork.image} alt={`${artwork.title} — ${artwork.note}`}/><span className="art-meta"><i>{c.number}</i><b>{artwork.title}</b><em>{c.name}</em></span></button> }
function BrandMark(){return <svg className="brand-mark" viewBox="0 0 42 42" aria-hidden="true"><path d="M8 6v30M8 7h18L14 21h20M8 36h18"/><path d="M29 7v29"/></svg>}
type IconName='north-east'|'east'|'west'|'south'|'close';
function StrokeIcon({name}:{name:IconName}){const paths:Record<IconName,string>={
  'north-east':'M6 18 18 6M8 6h10v10', east:'M5 12h14M14 7l5 5-5 5', west:'M19 12H5m5-5-5 5 5 5', south:'M12 5v14m-5-5 5 5 5-5', close:'M6 6l12 12M18 6 6 18'
};return <svg className="stroke-icon" viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]}/></svg>}
function Nav(){
  const [menu,setMenu]=useState(false);
  const [menuView,setMenuView]=useState<'main'|'works'>('main');
  const hash=useLocation();
  const closeMenu=()=>{setMenu(false);setMenuView('main')};
  useEffect(()=>{if(!menu)return;const close=(e:KeyboardEvent)=>e.key==='Escape'&&closeMenu();addEventListener('keydown',close);document.body.style.overflow='hidden';return()=>{removeEventListener('keydown',close);document.body.style.overflow=''}},[menu]);
  return <>
    <header>
      <a className="wordmark" href="#/" aria-label="Accueil — Emma, portfolio d’Emmanuel"><BrandMark/><span>EMMA</span></a>
      <nav><a className={hash.startsWith('#/works')?'active':''} href="#/works">Travaux</a><a className={hash==='#/about'?'active':''} href="#/about">Démarche</a><a className={hash==='#/contact'?'active':''} href="#/contact">Dossier</a></nav>
      <button className="menu-button" onClick={()=>{setMenu(!menu);if(menu)setMenuView('main')}} aria-expanded={menu}><span/>{menu?'Fermer':'Menu'}</button>
    </header>
    {menu&&<div className="full-menu" role="dialog" aria-label="Navigation">
      {menuView==='main' ? <div className="menu-panel" key="main"><p>Dossier de candidature — Brassart</p><a onClick={closeMenu} href="#/"><small>01</small><b>Accueil</b><i>Sélection</i></a><a onClick={closeMenu} href="#/about"><small>02</small><b>Démarche</b><i>Intention</i></a><button className="menu-works" onClick={()=>setMenuView('works')}><small>03</small><b>Travaux</b><i className="icon-label">Explorer <StrokeIcon name="east"/></i></button><a onClick={closeMenu} href="#/contact"><small>04</small><b>Dossier</b><i>Parcours</i></a></div> : <div className="menu-panel" key="works"><button className="menu-back" onClick={()=>setMenuView('main')}><StrokeIcon name="west"/> Retour</button><p>Travaux — explorer une pratique</p><a onClick={closeMenu} href="#/works"><small>00</small><b>Tous les travaux</b><i>Archives du dossier</i></a>{(Object.keys(collections) as Category[]).map(c=><a key={c} onClick={closeMenu} href={`#/collection/${c}`}><small>{collections[c].number}</small><b>{collections[c].name}</b><i>{collections[c].verb}</i></a>)}</div>}
    </div>}
  </>
}
function Home(){ const picks=[artworks[0],artworks.find(a=>a.category==='illustrations')!,artworks.find(a=>a.category==='photography')!,artworks.find(a=>a.category==='graphic-design')!,artworks.find(a=>a.category==='traditional-sketches')!]; return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">Dossier de candidature — Brassart · 2026</p><h1>EMMA</h1><p className="role">Assoko Essony Eddie Philippe Emmanuel<br/>Illustration & design graphique</p><a href="#/works" className="line-link">Découvrir les travaux <StrokeIcon name="south"/></a></div><img className="hero-art" src={artworks.find(a=>a.category==='illustrations')!.image} alt="Illustration sélectionnée du dossier d’Emmanuel"/><div className="hero-trait"/><p className="hero-statement">Regarder,<br/>chercher, raconter.</p></section><section className="intro split"><p className="eyebrow">01 — Intention</p><div><h2>Donner une forme<br/>à ce qui <i>m’interroge.</i></h2><p>Emma est le nom de travail d’Assoko Essony Eddie Philippe Emmanuel. Ce dossier réunit les images d’un jeune auteur passionné par l’illustration, le design graphique et la manière dont une image peut transmettre un message, attirer le regard ou raconter une histoire.</p><p>Du dessin d’observation au croquis, de l’illustration à la photographie et au graphisme, chaque série témoigne d’une pratique en développement. Elle garde la trace des essais, des recherches et de la curiosité qui nourrissent son regard.</p></div></section><section className="selected"><div className="section-head"><p className="eyebrow">02 — Sélection</p><h2>Travaux retenus</h2><a href="#/works" className="icon-link">Voir l’ensemble du dossier <StrokeIcon name="north-east"/></a></div><div className="editorial-grid">{picks.map(a=><ArtworkCard key={a.id} artwork={a} open={()=>go(`#/work/${a.id}`)}/>)}</div></section><section className="manifesto"><p>Ce dossier ne montre pas seulement des images terminées.</p><h2>Il porte l’ambition de devenir un auteur capable de créer des récits et des illustrations à l’identité visuelle affirmée.</h2></section><section className="chapters"><p className="eyebrow">03 — Champs de recherche</p>{(Object.keys(collections) as Category[]).map((c)=>{const art=artworks.find(a=>a.category===c)!; const x=collections[c];return <a href={`#/collection/${c}`} key={c} className="chapter"><span>{x.number}</span><img loading="lazy" src={art.image} alt=""/><b>{x.name}</b><i>{x.verb}</i><em><StrokeIcon name="north-east"/></em></a>})}</section><section className="cta"><p className="eyebrow">04 — Candidature Brassart</p><h2>Une pratique en mouvement,<br/>prête à <i>prendre de l’ampleur.</i></h2><a href="#/contact" className="round-link"><span>Voir le dossier</span><StrokeIcon name="north-east"/></a></section></main> }
function Works({category}:{category?:Category}){const [filter,setFilter]=useState<Category|'all'>(category??'all');const [list,setList]=useState(false);useEffect(()=>setFilter(category??'all'),[category]);const shown=filter==='all'?artworks:artworks.filter(a=>a.category===filter);return <main className="page works"><div className="page-intro"><p className="eyebrow">Dossier — {String(artworks.length).padStart(2,'0')} pièces</p><h1>{category?collections[category].name:'Travaux'}</h1><p>{category?collections[category].introduction:'Un ensemble de recherches et de travaux qui témoignent d’une pratique en développement.'}</p></div><div className="filters"><div>{<button className={filter==='all'?'on':''} onClick={()=>setFilter('all')}>Tout <small>{artworks.length}</small></button>}{(Object.keys(collections) as Category[]).map(c=><button key={c} onClick={()=>setFilter(c)} className={filter===c?'on':''}>{collections[c].name}<small>{artworks.filter(a=>a.category===c).length}</small></button>)}</div><button onClick={()=>setList(!list)} className="view-toggle">{list?'Grille':'Liste'} <StrokeIcon name="east"/></button></div><div className={`gallery ${list?'list':''}`}>{shown.map(a=><ArtworkCard key={a.id} artwork={a} open={()=>go(`#/work/${a.id}`)}/>)}</div></main>}
function Viewer({artwork}:{artwork:Artwork}){const index=artworks.indexOf(artwork); const c=collections[artwork.category];useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key==='Escape')history.back(); if(e.key==='ArrowRight')go(`#/work/${artworks[(index+1)%artworks.length].id}`); if(e.key==='ArrowLeft')go(`#/work/${artworks[(index-1+artworks.length)%artworks.length].id}`)};const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';addEventListener('keydown',h);return()=>{document.body.style.overflow=previousOverflow;removeEventListener('keydown',h)}},[index]);return <main className="viewer" role="dialog" aria-modal="true"><button className="close" onClick={()=>history.back()} aria-label="Fermer l’œuvre">Fermer <StrokeIcon name="close"/></button><button className="prev" onClick={()=>go(`#/work/${artworks[(index-1+artworks.length)%artworks.length].id}`)} aria-label="Œuvre précédente"><StrokeIcon name="west"/></button><figure><img src={artwork.image} alt={`${artwork.title} — ${artwork.note}`}/></figure><aside><p className="eyebrow">{c.number} — {c.name}</p><h1>{artwork.title}</h1><p>{artwork.note}</p><small>{String(index+1).padStart(2,'0')} / {String(artworks.length).padStart(2,'0')}</small></aside><button className="next" onClick={()=>go(`#/work/${artworks[(index+1)%artworks.length].id}`)} aria-label="Œuvre suivante"><StrokeIcon name="east"/></button></main>}
function About(){return <main className="page about"><div className="about-title"><p className="eyebrow">Démarche — Emma / Emmanuel</p><h1>Faire de l’image<br/>un espace de <i>recherche.</i></h1></div><div className="about-text"><p>Je suis un étudiant passionné par l’art, l’illustration et le design graphique.</p><p>Au fil de mon parcours, j’ai appris à comprendre comment une image peut transmettre un message, attirer le regard et raconter une histoire. Mon travail part souvent de l’observation, mais il avance aussi par le croquis, l’illustration, la photographie et le graphisme.</p><p>Je souhaite explorer des thèmes qui me sont parfois étrangers : la spiritualité, l’amour, la mort, la tristesse, l’humain ou encore la culture. Ce sont pour moi des territoires de recherche, des points de départ pour imaginer des récits et construire des images plus fortes.</p><p>Mon ambition est de devenir un auteur capable de créer des histoires et des illustrations avec une identité visuelle affirmée. Le nom Emma est devenu ma signature : il rassemble mes travaux personnels, scolaires et expérimentaux.</p><div className="about-approach"><div><small>01</small><b>Observer</b><span>Partir du réel, de la silhouette et du détail.</span></div><div><small>02</small><b>Raconter</b><span>Faire de l’image un espace de message et de récit.</span></div><div><small>03</small><b>Évoluer</b><span>Construire une identité visuelle par l’expérimentation.</span></div></div><div className="availability"><span>Objectif</span><b>Intégrer Brassart pour développer une pratique d’auteur</b></div></div><img className="about-image" src={artworks.find(a=>a.category==='traditional-sketches')!.image} alt="Croquis traditionnel du dossier d’Emmanuel"/></main>}
function Contact(){return <main className="page contact application-page"><p className="eyebrow">Motivations — Candidature Brassart</p><h1>Pourquoi rejoindre<br/><i>Brassart ?</i></h1><div className="contact-layout"><div className="motivation"><p>Je me nomme Assoko Essony Eddie Philippe Emmanuel, j’ai 20 ans et je souhaite aujourd’hui poursuivre ma formation au sein de Brassart. Titulaire d’un BTA, équivalent du baccalauréat, j’ai étudié pendant trois ans au CTAA — Centre Technique des Arts Appliqués — de Bingerville, en spécialité Communication visuelle / Arts graphiques.</p><p>Cette formation m’a permis d’explorer l’infographie, l’illustration et la publicité. Elle a surtout confirmé mon intérêt pour l’image : comprendre comment une illustration transmet un message, attire le regard et raconte une histoire.</p><p>Mon ambition est de devenir un auteur capable de créer des récits et des illustrations fortes, portés par une identité visuelle affirmée. Je souhaite aussi explorer des thèmes qui me sont parfois étrangers — la spiritualité, l’amour, la mort, la tristesse, l’humain ou la culture — pour en faire des matières de création.</p><p>Intégrer Brassart représente pour moi l’opportunité d’évoluer dans un environnement stimulant et exigeant, d’affiner mes compétences et de préparer mon avenir dans les métiers de l’illustration et du design graphique. Curieux, motivé et déterminé, je veux faire de cette passion un véritable projet professionnel.</p></div><div className="application-record"><div><small>Identité</small><b>Assoko Essony Eddie Philippe Emmanuel</b></div><div><small>Nom d’artiste</small><b>Emma</b></div><div><small>Formation</small><b>BTA — Communication visuelle / Arts graphiques</b></div><div><small>Établissement</small><b>CTAA, Bingerville</b></div><div><small>École visée</small><b>Brassart</b></div><div><small>Projet</small><b>Illustration, design graphique et création de récits visuels.</b></div></div></div></main>}
function Footer(){return <footer className="site-footer"><div className="footer-main"><a className="footer-brand" href="#/" aria-label="Retour à l’accueil"><BrandMark/><span>EMMA</span></a><p>Un dossier de candidature<br/>pour Brassart.</p><a className="footer-contact" href="#/contact"><span>Consulter le parcours</span><StrokeIcon name="north-east"/></a></div><div className="footer-base"><span>© 2026 Emmanuel</span><div><a href="#/works">Travaux</a><a href="#/about">Démarche</a><a href="#/contact">Dossier</a></div><span>Illustration & design graphique</span></div></footer>}
export function App(){
  const path=useLocation();
  useEffect(()=>{
    const targets=Array.from(document.querySelectorAll<HTMLElement>('.split,.selected,.manifesto,.chapters,.cta,.page-intro,.filters,.gallery,.about-text,.about-image,.contact-layout'));
    if(!targets.length || matchMedia('(prefers-reduced-motion: reduce)').matches){targets.forEach(el=>el.classList.add('is-visible'));return}
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -7% 0px'});
    targets.forEach(el=>observer.observe(el));
    return()=>observer.disconnect();
  },[path]);
  let page;const work=path.match(/^#\/work\/(.+)$/)?.[1];const collection=path.match(/^#\/collection\/(.+)$/)?.[1] as Category|undefined;
  if(work){const a=artworks.find(x=>x.id===work);page=a?<Viewer artwork={a}/>:<Works/>}else if(collection&&collections[collection])page=<Works category={collection}/>;else if(path==='#/works')page=<Works/>;else if(path==='#/about')page=<About/>;else if(path==='#/contact')page=<Contact/>;else page=<Home/>;
  return <><Nav/><div className={work?'viewer-route':'route-shell'} key={path}>{page}</div><Footer/></>
}
