import { FormEvent, useEffect, useMemo, useState } from 'react';

type Category = 'drawing' | 'sketches' | 'illustrations' | 'photography' | 'school-projects' | 'graphic-design' | 'traditional-sketches';
type Artwork = { id:string; title:string; note:string; originalFilename:string; category:Category; image:string; featured?:boolean; order:number };

const collections: Record<Category, {number:string; name:string; verb:string; introduction:string; accent:string}> = {
  drawing: {number:'01', name:'Dessins', verb:'Observer', accent:'graphite', introduction:'Études de visage, de main, d’anatomie et de présence. Le regard commence ici, par ce qui est vu.'},
  sketches: {number:'02', name:'Croquis', verb:'Chercher', accent:'paper', introduction:'Un laboratoire de lignes rapides, de postures et de recherches laissées volontairement ouvertes.'},
  illustrations: {number:'03', name:'Illustrations', verb:'Imaginer', accent:'vermilion', introduction:'Des images plus affirmées, où la couleur et la composition prolongent le geste du dessin.'},
  photography: {number:'04', name:'Photographie', verb:'Cadrer', accent:'night', introduction:'Des fragments retenus par le cadre : lumière, distance, rythme et détail.'},
  'school-projects': {number:'05', name:'Projets scolaires', verb:'Construire', accent:'ochre', introduction:'Affiches, systèmes et supports conçus dans le cadre de recherches appliquées.'},
  'graphic-design': {number:'06', name:'Design graphique', verb:'Communiquer', accent:'ink', introduction:'Une image pensée pour être lue, reconnue et faire circuler une idée.'},
  'traditional-sketches': {number:'07', name:'Croquis traditionnels', verb:'Tracer', accent:'earth', introduction:'La feuille, le bureau, le stylo : le temps du geste et la matière réelle.'}
};

const files: Record<Category, string[]> = {
  drawing:['1782435152728','observation','img-20260626-004004-104','anatomie','mains','1782414372620','portrait'],
  sketches:['1784077176551','1784077179368','1784077183491','1784077192873','1784077196263','1784077199192','1784077203887','1784077207687','1784077227077','1784077229966','1784077236145','1784077238456','1784077241017','1784077244198'],
  illustrations:['rahhhhh-ttt','jesus22','collabbbbbrr','mtl','hn','com-2025','number-1'],
  photography:['img-20260102-005847-245-70101640','img-20251231-113900-580-1944823730','img-20251230-164810-896-1119577469','img-20251230-164602-592-1371120361','img-20251230-162756-988-478238756','img-20251230-161949-969-63003246','img-20251230-161710-439-1189738396','img-20260330-152014-917','img-20260128-024752-107','img-20260128-024400-270','img-20260128-023245-329','img-20260128-011915-433','img-20260116-173108-986'],
  'school-projects':['1784541226481','affiche','affiche-femme-glissante','affiche-femme','affiche-lebron','affiche-mascotte','emballage-du-produit-cofi'],
  'graphic-design':['hn1','roua-copie','after-work-revisiter-orig','maquette-originel-de-dos','maquette-originel-h24','panini-etiquette-copie'],
  'traditional-sketches':['bic','img-20260320-220227-940','img-20260320-215246-220','img-20260320-215209-755','img-20241219-072301-22','img-20241219-133055-658','img-20250815-175339-354','img-20250815-174416-209','img-20250815-175842-361','img-20250815-180051-141']
};
const artworkCopy: Record<Category, Array<[string,string]>> = {
  drawing:[['Étude de visage','Un travail d’observation où le trait cherche avant tout la présence.'],['Observation','Une étude attentive du modèle, construite par les valeurs et les contours.'],['Figure en mouvement','Une silhouette saisie dans un moment de tension et d’équilibre.'],['Anatomie','Recherche autour de la structure du corps et de ses volumes.'],['Étude de mains','Une série consacrée aux gestes, aux articulations et à l’expression des mains.'],['Étude de figure','Une recherche de proportions, de rythme et de placement dans la page.'],['Portrait','Un visage traité comme une rencontre entre caractère et lumière.']],
  sketches:[['Recherche 01','Croquis de posture, direct et sans correction superflue.'],['Recherche 02','Étude de mouvement à partir d’une ligne continue.'],['Recherche 03','Une silhouette construite par masses et contrepoids.'],['Recherche 04','Variation autour de la pose et de l’espace négatif.'],['Recherche 05','Recherche rapide, pensée comme une note de carnet.'],['Recherche 06','Le trait s’attarde sur la torsion du corps et les plis.'],['Recherche 07','Une scène de figure, retenue dans l’énergie du croquis.'],['Recherche 08','Dessin d’observation où la ligne devient volume.'],['Recherche 09','Étude de présence et de posture.'],['Recherche 10','Une recherche de structure, de texture et de rythme.'],['Recherche 11','Croquis à l’encre bleue, entre étude anatomique et mouvement.'],['Recherche 12','Une figure esquissée avec économie de moyens.'],['Recherche 13','Recherche de composition autour du corps dans l’espace.'],['Recherche 14','Un instant de dessin, gardé vivant par les traits de construction.']],
  illustrations:[['Rupture','Une illustration sombre où le personnage devient le point de friction de l’image.'],['Figure sacrée','Une composition centrée sur le regard, la matière et le contraste.'],['Collaboration','Une image conçue comme un échange de styles et de sensibilités.'],['MTL','Illustration numérique à la palette dense et aux formes affirmées.'],['HN','Une figure stylisée, travaillée comme une présence graphique.'],['COM 2025','Une composition pensée pour l’impact, l’affiche et la lecture immédiate.'],['Number One','Une image typographique où le personnage et le signe se répondent.']],
  photography:[['Lumière basse','Un cadrage où la lumière pose le premier plan et le silence.'],['Matière','Roches, mousses et reliefs : une étude de texture naturelle.'],['Reflet','Une image tenue par les surfaces, la couleur et la profondeur.'],['En suspension','La lumière isole un détail et change l’échelle du regard.'],['Passage','Une photographie de rythme, entre espace construit et instant saisi.'],['Contour','Un fragment observé pour ses lignes, ses ombres et sa densité.'],['Éclat','Une composition attentive aux contrastes et à la vibration de la couleur.'],['Hors saison','Un paysage ou un détail traité comme une image autonome.'],['Bleu profond','Une recherche photographique autour d’une tonalité et de ses nuances.'],['Rythme urbain','L’architecture et la lumière organisent le cadre.'],['Après l’averse','Une image de détails, de reflets et de matière.'],['Veille','Un moment calme, construit par la lumière disponible.'],['Dernière lumière','Une photographie qui privilégie l’atmosphère à l’anecdote.']],
  'school-projects':[['Projet éditorial','Recherche d’image et de hiérarchie pour un support de communication.'],['Affiche','Une proposition typographique conçue pour être vue à distance.'],['Femme glissante','Affiche de mouvement, entre narration visuelle et composition.'],['Figure','Une image qui met le personnage au centre de la lecture.'],['LeBron','Une affiche sportive pensée autour de la présence et de l’impact.'],['Mascotte','Travail d’identité et de caractère pour une figure illustrée.'],['Cofi — emballage','Recherche de packaging : forme, couleur et reconnaissance du produit.']],
  'graphic-design':[['HN1','Affiche illustrée : un univers narratif, dense et frontal.'],['ROUA','Une composition graphique où l’image et le signe partagent l’espace.'],['After Work','Visuel d’événement pensé pour l’énergie, le contraste et la nuit.'],['Maquette — dos','Étude de placement graphique sur vêtement.'],['Maquette H24','Proposition textile construite autour d’un emblème central.'],['Étiquette Panini','Une étiquette qui joue avec le format, la couleur et l’objet.']],
  'traditional-sketches':[['BIC','Un dessin au stylo où l’accident du trait fait partie de l’image.'],['Étude au stylo 01','Recherche de matière et de densité par la répétition du trait.'],['Étude au stylo 02','Une figure construite lentement, entre hachures et contours.'],['Étude au stylo 03','Le stylo comme outil de précision et de mouvement.'],['Carnet — matin','Une étude de carnet, gardée dans sa spontanéité.'],['Carnet — figure','Une recherche au stylo autour d’une silhouette et de ses volumes.'],['Carnet — détail','Une image de proximité, attentive aux textures.'],['Carnet — pause','Une étude brève où le trait capture une posture.'],['Carnet — construction','Les lignes de recherche restent visibles et font partie de la composition.'],['Carnet — dernière page','Une étude finale, plus libre, entre observation et interprétation.']]
};
const originalExtensions:Record<Category,string> = {drawing:'png',sketches:'png',illustrations:'jpg',photography:'jpg','school-projects':'jpg','graphic-design':'jpg','traditional-sketches':'jpg'};
const artworks:Artwork[] = (Object.keys(files) as Category[]).flatMap(category => files[category].map((file,index) => {
  const [title,note] = artworkCopy[category][index] ?? [`Recherche ${index+1}`,'Une pièce issue du portfolio d’Emmanuel.'];
  return { id:`${category}-${index+1}`, title, note, originalFilename:`${String(index+1).padStart(2,'0')}-${file}.${originalExtensions[category]}`, category, image:`/artworks/${category}/${String(index+1).padStart(2,'0')}-${file}.webp`, featured:index===0, order:index+1 };
}));

function useLocation(){ const [hash,setHash]=useState(location.hash || '#/'); useEffect(()=>{const fn=()=>setHash(location.hash||'#/'); addEventListener('hashchange',fn); return()=>removeEventListener('hashchange',fn)},[]); return hash; }
const go=(path:string)=>{location.hash=path; window.scrollTo({top:0,behavior:'instant' as ScrollBehavior})};
function ArtworkCard({artwork, open}:{artwork:Artwork;open:()=>void}){ const c=collections[artwork.category]; return <button className={`art-card ${c.accent}`} onClick={open} aria-label={`Ouvrir ${artwork.title}`}><img loading="lazy" src={artwork.image} alt={`${artwork.title} — ${artwork.note}`}/><span className="art-meta"><i>{c.number}</i><b>{artwork.title}</b><em>{c.name}</em></span></button> }
function BrandMark(){return <svg className="brand-mark" viewBox="0 0 42 42" aria-hidden="true"><path d="M8 6v30M8 7h18L14 21h20M8 36h18"/><path d="M29 7v29"/></svg>}
function Nav(){
  const [menu,setMenu]=useState(false);
  const [menuView,setMenuView]=useState<'main'|'works'>('main');
  const hash=useLocation();
  const closeMenu=()=>{setMenu(false);setMenuView('main')};
  useEffect(()=>{if(!menu)return;const close=(e:KeyboardEvent)=>e.key==='Escape'&&closeMenu();addEventListener('keydown',close);document.body.style.overflow='hidden';return()=>{removeEventListener('keydown',close);document.body.style.overflow=''}},[menu]);
  return <>
    <header>
      <a className="wordmark" href="#/" aria-label="Accueil — Emma, portfolio d’Emmanuel"><BrandMark/><span>EMMA</span></a>
      <nav><a className={hash.startsWith('#/works')?'active':''} href="#/works">Œuvres</a><a className={hash==='#/about'?'active':''} href="#/about">À propos</a><a className={hash==='#/contact'?'active':''} href="#/contact">Contact</a></nav>
      <button className="menu-button" onClick={()=>{setMenu(!menu);if(menu)setMenuView('main')}} aria-expanded={menu}><span/>{menu?'Fermer':'Menu'}</button>
    </header>
    {menu&&<div className="full-menu" role="dialog" aria-label="Navigation">
      {menuView==='main' ? <div className="menu-panel" key="main"><p>Portfolio d’Emmanuel</p><a onClick={closeMenu} href="#/"><small>01</small><b>Accueil</b><i>La sélection</i></a><a onClick={closeMenu} href="#/about"><small>02</small><b>À propos</b><i>La démarche</i></a><button className="menu-works" onClick={()=>setMenuView('works')}><small>03</small><b>Œuvres</b><i>Explorer <span>→</span></i></button><a onClick={closeMenu} href="#/contact"><small>04</small><b>Contact</b><i>Échanger</i></a></div> : <div className="menu-panel" key="works"><button className="menu-back" onClick={()=>setMenuView('main')}>← Retour</button><p>Œuvres — choisir un chemin</p><a onClick={closeMenu} href="#/works"><small>00</small><b>Toutes les œuvres</b><i>Archives complètes</i></a>{(Object.keys(collections) as Category[]).map(c=><a key={c} onClick={closeMenu} href={`#/collection/${c}`}><small>{collections[c].number}</small><b>{collections[c].name}</b><i>{collections[c].verb}</i></a>)}</div>}
    </div>}
  </>
}
function Home(){ const picks=[artworks[0],artworks.find(a=>a.category==='illustrations')!,artworks.find(a=>a.category==='photography')!,artworks.find(a=>a.category==='graphic-design')!,artworks.find(a=>a.category==='traditional-sketches')!]; return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">Portfolio sélectionné — 2025 / 2026</p><h1>EMMA</h1><p className="role">Emmanuel — artiste visuel,<br/>dessinateur & graphiste</p><a href="#/works" className="line-link">Entrer dans les œuvres <span>↓</span></a></div><img className="hero-art" src={artworks.find(a=>a.category==='illustrations')!.image} alt="Illustration sélectionnée d’Emmanuel"/><div className="hero-trait"/><p className="hero-statement">Entre le trait<br/>et la matière.</p></section><section className="intro split"><p className="eyebrow">01 — Introduction</p><div><h2>Emma observe,<br/><i>déconstruit</i> et recompose.</h2><p>Emma est le nom de travail d’Emmanuel : une signature courte pour une pratique qui reste ancrée dans le regard, le geste et le temps passé à chercher.</p><p>Son travail traverse le dessin d’observation, le croquis, l’illustration, la photographie et le design graphique. Ce portfolio rassemble des recherches, des projets personnels et des créations appliquées, sans effacer le processus qui les a fait naître.</p></div></section><section className="selected"><div className="section-head"><p className="eyebrow">02 — Sélection</p><h2>Œuvres choisies</h2><a href="#/works">Voir toutes les œuvres ↗</a></div><div className="editorial-grid">{picks.map(a=><ArtworkCard key={a.id} artwork={a} open={()=>go(`#/work/${a.id}`)}/>)}</div></section><section className="manifesto"><p>Le dessin n’est pas uniquement une image terminée.</p><h2>C’est une manière de regarder, de comprendre et de laisser une trace.</h2></section><section className="chapters"><p className="eyebrow">03 — Disciplines</p>{(Object.keys(collections) as Category[]).map((c)=>{const art=artworks.find(a=>a.category===c)!; const x=collections[c];return <a href={`#/collection/${c}`} key={c} className="chapter"><span>{x.number}</span><img loading="lazy" src={art.image} alt=""/><b>{x.name}</b><i>{x.verb}</i><em>↗</em></a>})}</section><section className="cta"><p className="eyebrow">04 — Échange</p><h2>Un projet, une commande,<br/>une collaboration ?</h2><a href="#/contact" className="round-link">Parlons-en <span>↗</span></a></section></main> }
function Works({category}:{category?:Category}){const [filter,setFilter]=useState<Category|'all'>(category??'all');const [list,setList]=useState(false);useEffect(()=>setFilter(category??'all'),[category]);const shown=filter==='all'?artworks:artworks.filter(a=>a.category===filter);return <main className="page works"><div className="page-intro"><p className="eyebrow">Archives — {String(artworks.length).padStart(2,'0')} pièces</p><h1>{category?collections[category].name:'Œuvres'}</h1><p>{category?collections[category].introduction:'Une collection de recherches, d’images finalisées et de créations appliquées.'}</p></div><div className="filters"><div>{<button className={filter==='all'?'on':''} onClick={()=>setFilter('all')}>Tout <small>{artworks.length}</small></button>}{(Object.keys(collections) as Category[]).map(c=><button key={c} className={filter===c?'on':''} onClick={()=>setFilter(c)}>{collections[c].name}<small>{artworks.filter(a=>a.category===c).length}</small></button>)}</div><button onClick={()=>setList(!list)} className="view-toggle">{list?'Grille':'Liste'} ↗</button></div><div className={`gallery ${list?'list':''}`}>{shown.map(a=><ArtworkCard key={a.id} artwork={a} open={()=>go(`#/work/${a.id}`)}/>)}</div></main>}
function Viewer({artwork}:{artwork:Artwork}){const index=artworks.indexOf(artwork); const c=collections[artwork.category];useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key==='Escape')history.back(); if(e.key==='ArrowRight')go(`#/work/${artworks[(index+1)%artworks.length].id}`); if(e.key==='ArrowLeft')go(`#/work/${artworks[(index-1+artworks.length)%artworks.length].id}`)};addEventListener('keydown',h);return()=>removeEventListener('keydown',h)},[index]);return <main className="viewer" role="dialog" aria-modal="true"><button className="close" onClick={()=>history.back()}>Fermer ×</button><button className="prev" onClick={()=>go(`#/work/${artworks[(index-1+artworks.length)%artworks.length].id}`)}>←</button><figure><img src={artwork.image} alt={`${artwork.title} — ${artwork.note}`}/></figure><aside><p className="eyebrow">{c.number} — {c.name}</p><h1>{artwork.title}</h1><p>{artwork.note}</p><small>{String(index+1).padStart(2,'0')} / {String(artworks.length).padStart(2,'0')}</small></aside><button className="next" onClick={()=>go(`#/work/${artworks[(index+1)%artworks.length].id}`)}>→</button></main>}
function About(){return <main className="page about"><div className="about-title"><p className="eyebrow">À propos</p><h1>Faire de l’image<br/>un lieu de <i>présence.</i></h1></div><div className="about-text"><p>Emma, c’est Emmanuel : un artiste visuel qui place le dessin au centre de sa pratique.</p><p>Son travail part souvent d’une observation précise — un visage, une posture, une matière, une lumière — avant de circuler entre croquis traditionnel, illustration numérique, photographie et design graphique. Il ne cherche pas à lisser les recherches : les traits de construction, les essais et les accidents restent visibles, parce qu’ils racontent aussi l’image.</p><p>Le nom Emma est devenu sa signature. Il rassemble des projets personnels, des pièces réalisées en cours et des expérimentations plus libres, avec la même attention portée à la présence, au rythme et à la composition.</p><div className="availability"><span>Ouvert aux</span><b>Commandes · collaborations · projets graphiques</b></div></div><img className="about-image" src={artworks.find(a=>a.category==='traditional-sketches')!.image} alt="Croquis traditionnel réalisé par Emmanuel"/></main>}
function Contact(){const [sent,setSent]=useState(false);function submit(e:FormEvent){e.preventDefault();setSent(true)}return <main className="page contact"><p className="eyebrow">Contact</p><h1>Une idée mérite<br/>d’être <i>dessinée.</i></h1><div className="contact-layout"><p>Pour une commande, une collaboration ou simplement échanger autour d’un projet, écrivez à Emma. Le formulaire est prêt pour Netlify Forms.</p>{sent?<div className="thanks"><h2>Message préparé.</h2><p>Merci — Emma reviendra vers vous dès que possible.</p></div>:<form name="contact-emma" data-netlify="true" onSubmit={submit}><input type="hidden" name="form-name" value="contact-emma"/><label>Votre nom<input required name="name" autoComplete="name"/></label><label>Votre e-mail<input required type="email" name="email" autoComplete="email"/></label><label>Votre demande<select name="request"><option>Commande d’illustration</option><option>Portrait</option><option>Projet graphique</option><option>Collaboration</option><option>Photographie</option><option>Autre</option></select></label><label>Budget indicatif <input name="budget" placeholder="Facultatif"/></label><label>Votre message<textarea required name="message" rows={5}/></label><button className="submit">Envoyer le message <span>↗</span></button></form>}</div></main>}
export function App(){const path=useLocation();let page;const work=path.match(/^#\/work\/(.+)$/)?.[1];const collection=path.match(/^#\/collection\/(.+)$/)?.[1] as Category|undefined;if(work){const a=artworks.find(x=>x.id===work);page=a?<Viewer artwork={a}/>:<Works/>}else if(collection&&collections[collection])page=<Works category={collection}/>;else if(path==='#/works')page=<Works/>;else if(path==='#/about')page=<About/>;else if(path==='#/contact')page=<Contact/>;else page=<Home/>;return <><Nav/><div className="route-shell" key={path}>{page}</div><footer><span>EMMA — Portfolio 2025 / 2026</span><a href="#/contact">Contact ↗</a></footer></>}
