import { FormEvent, useEffect, useMemo, useState } from 'react';

type Category = 'drawing' | 'sketches' | 'illustrations' | 'photography' | 'school-projects' | 'graphic-design' | 'traditional-sketches';
type Artwork = { id:string; title:string; originalFilename:string; category:Category; image:string; featured?:boolean; order:number };

const collections: Record<Category, {number:string; name:string; verb:string; introduction:string; accent:string}> = {
  drawing: {number:'01', name:'Dessins', verb:'Observer', accent:'graphite', introduction:'Études de visage, de main, d’anatomie et de présence. Le regard commence ici, par ce qui est vu.'},
  sketches: {number:'02', name:'Croquis', verb:'Chercher', accent:'paper', introduction:'Un laboratoire de lignes rapides, de postures et de recherches laissées volontairement ouvertes.'},
  illustrations: {number:'03', name:'Illustrations', verb:'Imaginer', accent:'vermilion', introduction:'Des images plus affirmées, où la couleur et la composition prolongent le geste du dessin.'},
  photography: {number:'04', name:'Photographie', verb:'Cadrer', accent:'night', introduction:'Des fragments retenus par le cadre : lumière, distance, rythme et détail.'},
  'school-projects': {number:'05', name:'Projets scolaires', verb:'Construire', accent:'ochre', introduction:'Affiches, systèmes et supports conçus dans le cadre de recherches appliquées.'},
  'graphic-design': {number:'06', name:'Design graphique', verb:'Communiquer', accent:'ink', introduction:'Une image pensée pour être lue, reconnue et faire circuler une idée.'},
  'traditional-sketches': {number:'07', name:'Croquis traditionnels', verb:'Tracer', accent:'earth', introduction:'La feuille, le bureau, le stylo : le temps du geste et la matière réelle.'}
};

const files: Record<Category, string[]> = {
  drawing:['1782435152728','observation','img-20260626-004004-104','anatomie','mains','1782414372620','portrait'],
  sketches:['1784077176551','1784077179368','1784077183491','1784077192873','1784077196263','1784077199192','1784077203887','1784077207687','1784077227077','1784077229966','1784077236145','1784077238456','1784077241017','1784077244198'],
  illustrations:['rahhhhh-ttt','jesus22','collabbbbbrr','mtl','hn','com-2025','number-1'],
  photography:['img-20260102-005847-245-70101640','img-20251231-113900-580-1944823730','img-20251230-164810-896-1119577469','img-20251230-164602-592-1371120361','img-20251230-162756-988-478238756','img-20251230-161949-969-63003246','img-20251230-161710-439-1189738396','img-20260330-152014-917','img-20260128-024752-107','img-20260128-024400-270','img-20260128-023245-329','img-20260128-011915-433','img-20260116-173108-986'],
  'school-projects':['1784541226481','affiche','affiche-femme-glissante','affiche-femme','affiche-lebron','affiche-mascotte','emballage-du-produit-cofi'],
  'graphic-design':['hn1','roua-copie','after-work-revisiter-orig','maquette-originel-de-dos','maquette-originel-h24','panini-etiquette-copie'],
  'traditional-sketches':['bic','img-20260320-220227-940','img-20260320-215246-220','img-20260320-215209-755','img-20241219-072301-22','img-20241219-133055-658','img-20250815-175339-354','img-20250815-174416-209','img-20250815-175842-361','img-20250815-180051-141']
};
const workingTitles: Record<Category,string[]> = {
  drawing:['Étude I','Observation','Figure silencieuse','Anatomie','Étude de mains','Étude II','Portrait'], sketches:['Recherche I','Recherche II','Recherche III','Recherche IV','Recherche V'], illustrations:['Composition I','Présence','Collaboration','Fragment coloré','Figure','Composition II','Number One'], photography:['Sans titre, 01','Sans titre, 02','Sans titre, 03'], 'school-projects':['Projet graphique','Affiche','Affiche — mouvement','Affiche — figure','Affiche LeBron','Affiche mascotte','Packaging Cofi'], 'graphic-design':['HN1','ROUA','After Work','Maquette — dos','Maquette H24','Étiquette Panini'], 'traditional-sketches':['BIC','Étude au stylo','Étude au stylo II']
};
const originalExtensions:Record<Category,string> = {drawing:'png',sketches:'png',illustrations:'jpg',photography:'jpg','school-projects':'jpg','graphic-design':'jpg','traditional-sketches':'jpg'};
const artworks:Artwork[] = (Object.keys(files) as Category[]).flatMap(category => files[category].map((file,index) => ({ id:`${category}-${index+1}`, title:workingTitles[category][index] ?? `Recherche ${index+1}`, originalFilename:`${String(index+1).padStart(2,'0')}-${file}.${originalExtensions[category]}`, category, image:`/artworks/${category}/${String(index+1).padStart(2,'0')}-${file}.webp`, featured:index===0, order:index+1 })));

function useLocation(){ const [hash,setHash]=useState(location.hash || '#/'); useEffect(()=>{const fn=()=>setHash(location.hash||'#/'); addEventListener('hashchange',fn); return()=>removeEventListener('hashchange',fn)},[]); return hash; }
const go=(path:string)=>{location.hash=path; window.scrollTo({top:0,behavior:'instant' as ScrollBehavior})};
function ArtworkCard({artwork, open}:{artwork:Artwork;open:()=>void}){ const c=collections[artwork.category]; return <button className={`art-card ${c.accent}`} onClick={open} aria-label={`Ouvrir ${artwork.title}`}><img loading="lazy" src={artwork.image} alt={`${artwork.title}, ${c.name.toLowerCase()} par Emma`}/><span className="art-meta"><i>{c.number}</i><b>{artwork.title}</b><em>{c.name}</em></span></button> }
function Nav(){const [menu,setMenu]=useState(false); const hash=useLocation(); useEffect(()=>{if(!menu)return; const close=(e:KeyboardEvent)=>e.key==='Escape'&&setMenu(false); addEventListener('keydown',close); document.body.style.overflow='hidden'; return()=>{removeEventListener('keydown',close);document.body.style.overflow=''}},[menu]);return <><header><a className="wordmark" href="#/" aria-label="Accueil Emma">EMMA<span>•</span></a><nav><a className={hash.startsWith('#/works')?'active':''} href="#/works">Œuvres</a><a className={hash==='#/about'?'active':''} href="#/about">À propos</a><a className={hash==='#/contact'?'active':''} href="#/contact">Contact</a></nav><button className="menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu}><span/>{menu?'Fermer':'Menu'}</button></header>{menu&&<div className="full-menu"><p>Explorer les chapitres</p>{(Object.keys(collections) as Category[]).map(c=><a key={c} onClick={()=>setMenu(false)} href={`#/collection/${c}`}><small>{collections[c].number}</small><b>{collections[c].name}</b><i>{collections[c].verb}</i></a>)}</div>}</>}
function Home(){ const picks=[artworks[0],artworks.find(a=>a.category==='illustrations')!,artworks.find(a=>a.category==='photography')!,artworks.find(a=>a.category==='graphic-design')!,artworks.find(a=>a.category==='traditional-sketches')!]; return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">Portfolio sélectionné — 2025 / 2026</p><h1>EMMA</h1><p className="role">Artiste visuelle<br/>& dessinatrice</p><a href="#/works" className="line-link">Entrer dans les œuvres <span>↓</span></a></div><img className="hero-art" src={artworks.find(a=>a.category==='illustrations')!.image} alt="Illustration sélectionnée d’Emma"/><div className="hero-trait"/><p className="hero-statement">Entre le trait<br/>et la matière.</p></section><section className="intro split"><p className="eyebrow">01 — Introduction</p><div><h2>Emma observe,<br/><i>déconstruit</i> et recompose.</h2><p>Son travail traverse le dessin d’observation, le croquis, l’illustration, la photographie et le design graphique. Chaque image devient un terrain d’exploration où le geste, la composition et la matière dialoguent.</p><p>Ce portfolio rassemble des recherches, des projets personnels et des créations appliquées, sans effacer le processus qui leur a donné naissance.</p></div></section><section className="selected"><div className="section-head"><p className="eyebrow">02 — Sélection</p><h2>Œuvres choisies</h2><a href="#/works">Voir toutes les œuvres ↗</a></div><div className="editorial-grid">{picks.map((a,i)=><ArtworkCard key={a.id} artwork={a} open={()=>go(`#/work/${a.id}`)}/>)}</div></section><section className="manifesto"><p>Le dessin n’est pas uniquement une image terminée.</p><h2>C’est une manière de regarder, de comprendre et de laisser une trace.</h2></section><section className="chapters"><p className="eyebrow">03 — Disciplines</p>{(Object.keys(collections) as Category[]).map((c)=>{const art=artworks.find(a=>a.category===c)!; const x=collections[c];return <a href={`#/collection/${c}`} key={c} className="chapter"><span>{x.number}</span><img loading="lazy" src={art.image} alt=""/><b>{x.name}</b><i>{x.verb}</i><em>↗</em></a>})}</section><section className="cta"><p className="eyebrow">04 — Échange</p><h2>Un projet, une commande,<br/>une collaboration ?</h2><a href="#/contact" className="round-link">Parlons-en <span>↗</span></a></section></main> }
function Works({category}:{category?:Category}){const [filter,setFilter]=useState<Category|'all'>(category??'all');const [list,setList]=useState(false);useEffect(()=>setFilter(category??'all'),[category]);const shown=filter==='all'?artworks:artworks.filter(a=>a.category===filter);return <main className="page works"><div className="page-intro"><p className="eyebrow">Archives — {String(artworks.length).padStart(2,'0')} pièces</p><h1>{category?collections[category].name:'Œuvres'}</h1><p>{category?collections[category].introduction:'Une collection de recherches, d’images finalisées et de créations appliquées.'}</p></div><div className="filters"><div>{<button className={filter==='all'?'on':''} onClick={()=>setFilter('all')}>Tout <small>{artworks.length}</small></button>}{(Object.keys(collections) as Category[]).map(c=><button key={c} className={filter===c?'on':''} onClick={()=>setFilter(c)}>{collections[c].name}<small>{artworks.filter(a=>a.category===c).length}</small></button>)}</div><button onClick={()=>setList(!list)} className="view-toggle">{list?'Grille':'Liste'} ↗</button></div><div className={`gallery ${list?'list':''}`}>{shown.map(a=><ArtworkCard key={a.id} artwork={a} open={()=>go(`#/work/${a.id}`)}/>)}</div></main>}
function Viewer({artwork}:{artwork:Artwork}){const index=artworks.indexOf(artwork); const c=collections[artwork.category];useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key==='Escape')history.back(); if(e.key==='ArrowRight')go(`#/work/${artworks[(index+1)%artworks.length].id}`); if(e.key==='ArrowLeft')go(`#/work/${artworks[(index-1+artworks.length)%artworks.length].id}`)};addEventListener('keydown',h);return()=>removeEventListener('keydown',h)},[index]);return <main className="viewer" role="dialog" aria-modal="true"><button className="close" onClick={()=>history.back()}>Fermer ×</button><button className="prev" onClick={()=>go(`#/work/${artworks[(index-1+artworks.length)%artworks.length].id}`)}>←</button><figure><img src={artwork.image} alt={`${artwork.title}, ${c.name.toLowerCase()} par Emma`}/></figure><aside><p className="eyebrow">{c.number} — {c.name}</p><h1>{artwork.title}</h1><p>Œuvre sélectionnée dans le portfolio d’Emma. Les informations techniques seront ajoutées lorsqu’elles seront disponibles.</p><small>{String(index+1).padStart(2,'0')} / {String(artworks.length).padStart(2,'0')}</small></aside><button className="next" onClick={()=>go(`#/work/${artworks[(index+1)%artworks.length].id}`)}>→</button></main>}
function About(){return <main className="page about"><div className="about-title"><p className="eyebrow">À propos</p><h1>Faire de l’image<br/>un lieu de <i>présence.</i></h1></div><div className="about-text"><p>Emma développe une pratique visuelle centrée sur l’observation, le mouvement et la composition.</p><p>Elle explore aussi bien le dessin traditionnel que l’illustration numérique, la photographie et le design graphique. Son travail alterne recherches personnelles et projets appliqués, avec une attention particulière portée aux expressions, aux silhouettes et aux rapports entre image et support.</p><div className="availability"><span>Disponibilités</span><b>Commandes · collaborations · projets graphiques</b></div></div><img className="about-image" src={artworks.find(a=>a.category==='traditional-sketches')!.image} alt="Croquis traditionnel d’Emma"/></main>}
function Contact(){const [sent,setSent]=useState(false);function submit(e:FormEvent){e.preventDefault();setSent(true)}return <main className="page contact"><p className="eyebrow">Contact</p><h1>Une idée mérite<br/>d’être <i>dessinée.</i></h1><div className="contact-layout"><p>Pour une commande, une collaboration ou simplement échanger autour d’un projet, écrivez à Emma. Le formulaire est prêt pour Netlify Forms.</p>{sent?<div className="thanks"><h2>Message préparé.</h2><p>Merci — Emma reviendra vers vous dès que possible.</p></div>:<form name="contact-emma" data-netlify="true" onSubmit={submit}><input type="hidden" name="form-name" value="contact-emma"/><label>Votre nom<input required name="name" autoComplete="name"/></label><label>Votre e-mail<input required type="email" name="email" autoComplete="email"/></label><label>Votre demande<select name="request"><option>Commande d’illustration</option><option>Portrait</option><option>Projet graphique</option><option>Collaboration</option><option>Photographie</option><option>Autre</option></select></label><label>Budget indicatif <input name="budget" placeholder="Facultatif"/></label><label>Votre message<textarea required name="message" rows={5}/></label><button className="submit">Envoyer le message <span>↗</span></button></form>}</div></main>}
export function App(){const path=useLocation();let page;const work=path.match(/^#\/work\/(.+)$/)?.[1];const collection=path.match(/^#\/collection\/(.+)$/)?.[1] as Category|undefined;if(work){const a=artworks.find(x=>x.id===work);page=a?<Viewer artwork={a}/>:<Works/>}else if(collection&&collections[collection])page=<Works category={collection}/>;else if(path==='#/works')page=<Works/>;else if(path==='#/about')page=<About/>;else if(path==='#/contact')page=<Contact/>;else page=<Home/>;return <><Nav/>{page}<footer><span>EMMA — Portfolio 2025 / 2026</span><a href="#/contact">Contact ↗</a></footer></>}
